name: ice_and_fire_app
description: A Flutter app using An API of Ice and Fire.

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  provider: ^6.0.5
  google_fonts: ^5.0.0
environment:
  sdk: '^3.5.0'

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  assets:
    - images/